### PR TITLE
Support Puppet 5 & 6 + stdlib 5.0

### PR DESCRIPTION
**Pull request by ekohl**
This updates the testing infrastructure to support current versions.

Fixes GH-15

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]

**Comment by ekohl** [comment]
I forgot one change in Rakefile. Updating.

**Comment by JAORMX** [comment]
@locknut seems I don't have permission to merge this patch. Could you check it out or grant me permission to do such a thing?

**Comment by JAORMX** [comment]
@locknut what do you think?

**Comment by ekohl** [comment]
Should be good to merge now.

**Pull request merged**
